from pydantic import BaseModel
from typing import Annotated


class ModelInput(BaseModel):
    image: Annotated[str | None, "X-ray image from the user."] = None
    ground_truth: Annotated[
        str | None, "Report generated by the human expert radiologist."
    ] = None


class ModelOutput(BaseModel):
    generated_report: Annotated[
        str | None, "Generated report from the X-ray image."
    ] = None
