from pydantic import BaseModel
from typing import Annotated, Union

class ModelInput(BaseModel):
    image: Annotated[Union[str, None], "X-ray image from the user."] = None
    ground_truth: Annotated[Union[str, None], "Report generated by the human expert radiologist."] = None


class ModelOutput(BaseModel):
    generated_report: Annotated[Union[str, None], "Generated report from the X-ray image."] = None
